#!/bin/bash

set -o errexit -o nounset -o pipefail

source venv/bin/activate

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already deploying >&2
    exit 1
fi

gixy nginx/nginx.conf

remote=root@ams.nominatim.grapheneos.org

rsync -pcv --chmod=644 --fsync --preallocate nginx/{nginx.conf,mime.types} $remote:/etc/nginx/
ssh $remote systemctl reload nginx

rsync -rpcv --delete --chmod=D755,F644 --fsync --preallocate systemd/system/nominatim.service.d $remote:/etc/systemd/system/

rsync -pcv --chmod=600 --chown postgres:postgres --fsync --preallocate postgres/data/{pg_hba,pg_ident,postgresql}.conf $remote:/var/lib/postgres/data/
