[Unit]
After=postgresql.service
Requires=postgresql.service

[Service]
ExecStart=
ExecStart=/usr/bin/gunicorn -b unix:/run/nominatim.sock -w 32 -k uvicorn.workers.UvicornWorker nominatim_api.server.falcon.server:run_wsgi
