[Unit]
After=postgresql.service
Requires=postgresql.service

[Service]
CapabilityBoundingSet=
ExecStart=
ExecStart=/usr/bin/gunicorn --control-socket /run/nominatim/gunicorn.ctl -b unix:/run/nominatim.sock -w 32 -k asgi --keep-alive 65 nominatim_api.server.falcon.server:run_wsgi()
IPAddressDeny=any
LockPersonality=yes
NoNewPrivileges=yes
PrivateDevices=yes
PrivateIPC=yes
PrivateNetwork=yes
ProcSubset=pid
ProtectClock=yes
ProtectControlGroups=yes
ProtectHome=yes
ProtectHostname=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectProc=invisible
ProtectSystem=strict
RemoveIPC=yes
Restart=always
RestartMaxDelaySec=10s
RestartSec=100ms
RestartSteps=5
RestrictAddressFamilies=AF_UNIX
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
RuntimeDirectory=nominatim
RuntimeDirectoryMode=700
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@obsolete @privileged @resources
UMask=0077
